-- Supabase SQL: create orders and order_items tables

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text,
  customer_phone text,
  customer_address text,
  wilaya text,
  shipping_cost numeric(10,2) default 0,
  subtotal numeric(10,2) not null,
  total numeric(10,2) not null,
  status text not null default 'pending',
  inserted_at timestamptz default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  name text,
  price numeric(10,2) not null,
  quantity int not null,
  inserted_at timestamptz default now()
);
