-- Supabase SQL: create products table (schema only)
-- Sample data is generated dynamically via the admin panel

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10,2) not null,
  image_url text,
  created_at timestamptz default now()
);
